### ISSUE TITLE
Conda forge breaks lxml 

### ISSUE THREAD

**Issue by danich1** [greenelab/snorkeling#19]
There is a bug when trying to rely on conda forge to install the python module lxml. Right now if one were to create the conda environment and import lxml.etree, the following error will occur:

>Traceback (most recent call last):
> File "<string>", line 1, in <module>
> ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

Therefore, I argue that we move lxml to be a pip dependency as installing lxml through that way fixes it.

**Comment by dhimmel** [comment]
Lot's of related issues on GitHub:

+ https://github.com/chapmanb/bcbio-nextgen/issues/1878
+ https://github.com/poldracklab/mriqc/issues/371
+ https://github.com/conda-forge/geopandas-feedstock/issues/21

`lxml` via pip could be a good workaround. It looks like you may also be able to specify `icu=56.1`.

**Comment by gwaybio** [comment]
Just encountered a similar situation and landed here searching for solutions. I was able to solve the conda forge error:

```
>>> import igraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gway/anaconda3/envs/gea_community_detection/lib/python2.7/site-packages/igraph/__init__.py", line 34, in <module>
    from igraph._igraph import *
ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
```
by specifying `icu=58` in the environment.yml file in greenelab/GEA_Community_Detection#23
