### ISSUE TITLE
Specifying a conda environment

### ISSUE THREAD

**Issue by dhimmel** [greenelab/snorkeling#3]
It would be great to create a conda environment for this project. The environment should use Python 2.7 rather than 3.6 (see https://github.com/HazyResearch/snorkel/issues/509).

In private communication, @ajratner wrote:

> In particular, if you're willing to absorb the bumps of code being actively developed, you can check out the dev branch: https://github.com/HazyResearch/snorkel/tree/dev

Also see @ajratner's [note here](https://thinklab.com/discussion/brainstorming-future-directions-for-hetionet/227#note-284):

> However, it's certainly still at a stage where our active involvement–both for help/bugfixes and active collaboration on code development–seems to be a big help, in part since the code is evolving so rapidly in response to feedback. We're hoping that it will begin to increasingly stabilize soon; and any feedback you have for us on how we could make it easier to use would be greatly appreciated, either via github issues, a skype call, or on this platform!

@danich1, for these reasons I think we may want to use the a dev version of snorkel. You can specify this in the conda `environment.yml` using a `pip` installation. Example at http://stackoverflow.com/a/32799944/4651668.

**Comment by dhimmel** [comment]
You'll want to include the packages in https://github.com/HazyResearch/snorkel/blob/dev/python-package-requirement.txt, which currently contains:

```
bs4
futures
ipywidgets
jupyter
lxml
matplotlib
nltk
numba
numbskull
numpy>=1.11
pandas
requests
scipy>=0.18
sklearn
sqlalchemy>=1.0.14
theano>=0.8.2
```

Most of these are in the anaconda channel. But the ones that are not, can be installed with `pip`.

**Comment by danich1** [comment]
Got it. So far have all installed just working on that bug I mentioned earlier.

**Comment by ajratner** [comment]
As a heads up we're probably going to merge a big PR into dev, and then soon after merge this into master as a new release of Snorkel, within the next 1-2 weeks; just so you know!  Any other issues here with setup?

**Comment by danich1** [comment]
No issues to report now. Excited for the update!

**Comment by dhimmel** [comment]
Closed by https://github.com/greenelab/snorkeling/pull/4 in 549ef4509ce6b886ae9628fe94acd595c9559aa1.
