### ISSUE TITLE
Gathering Tagged Pubmed Copora

### ISSUE THREAD

**Issue by danich1** [greenelab/snorkeling#7]
The goal here is to have a full listing of tagged pubmed abstracts (full text down the road). A few key issues to sort out are:

- [ ] What tagging resources are the best for tagging abstracts? (currently using [Pubtator](https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/PubTator/), but skeptical of its scaling abilities)
- [ ] What is the best format to parse these tagged abstracts? (currently using Pubtator's xml format, but amenable to other formats)

If I am missing anything, feel free to let me know: @dhimmel or @cgreene.

**Comment by ajratner** [comment]
Hey @dhimmel @danich1  I just added you to a repo I had started for preprocessing the PubTator tags and storing in snorkel format.  It's not finished yet unfortunately...

- It needs to be updated for the newest release
- Has a few lingering parsing bugs (extremely minimal effect, but easy to correct)
- Need to set up some way to share the parsed files like Git LFS

I still plan to do this stuff, I'm just very behind on stuff for an upcoming deadline, so I figured I'd add you to the repo in case you want to take a look at before then!
